name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Pega o código do repositório
      - uses: actions/checkout@v4

      # Passo 2: Configura o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Passo 3: Roda o build e os testes
      - name: Build with Maven
        run: mvn -B package --file pom.xml